### ISSUE TITLE
Refatoração do código para inglês

### ISSUE THREAD

**Issue by luizgustavodarossi** [SergioTEC/to-do-list#1]
Acredito que seria benéfico refatorar o código para inglês para torná-lo mais acessível para desenvolvedores internacionais e melhorar sua estrutura interna. Isso pode ajudar a evitar a deterioração do código ao longo do tempo e torná-lo mais fácil de manter e entender.

**Comment by gabrieldeespindula** [comment]
Outro ponto interessante seria começar a utilizar os commits em inglês e além disso agrupar os commits em PRs

**Comment by nortonbatista** [comment]
Bom já que estamos tocando nesse ponto, seria legal alterar o nome do aquivo [estilo.css](https://github.com/SergioTEC/to-do-list/blob/main/estilo.css) para `styles.css`

**Comment by SergioTEC** [comment]
@luizgustavodarossi @gabrieldeespindula @nortonbatista @ally1002 
Obrigado pelas dicas pessoal, irei providenciar as alterações.
